### PR TITLE
Feature/render form directive

### PR DESCRIPTION
**Pull request by fespinoza**
so, the first step is to render the form, from a component, using the JSON and tying the model to the form

screen shot 2015-03-22 at 1 05 45 am

### CODE REVIEW

**Comment by jgorset** [comment]
@fespinoza! You're awesome!

**Comment by jgorset** [comment]
:sparkles: :cake: :sparkles:

**Comment by mathiasbno** [comment]
:+1:

**Comment by sindrenm** [comment]
Many cake. Very calories.

**Pull request merged**
